### ISSUE TITLE
newLocation setter does not work with WU API

### ISSUE THREAD

**Issue by jpawlowski** [fhem/Weather#8]
Testing the new setter, it will give me the following error:

```
this API is not newLocation supported
```

However, https://github.com/fhem/Weather/pull/7 should have handled this but apparently it didn't.

Also, I would like to suggest to rename the setter to `tempLocation` as the word _new_ in it is kind of miss leading and confusing as somebody will likely assume it is a permanent change.

**Comment by CoolTuxNet** [comment]
new weather version online. support for wunderground newLocation setter

**Comment by jpawlowski** [comment]
@LeonGaultier can you name the respective commit here so it is linked?
You may even state in the comment of your commit this issue ID to automatically link it. It can even be closed by that by using a term like `closes issue #8`.

By doing so you automatically document changes very easily and transparent.

Also see
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by CoolTuxNet** [comment]
Sorry zu spät eingefallen das das auch geht :-)

**Comment by jpawlowski** [comment]
Doing it for you:

Commit c45d3be0287d31ff3f52626e62052a8858c9715c resolved this issue.
